FROM amazon/aws-cli:latest

# Define environment variables
ENV AWS_ACCESS_KEY_ID=NA 
ENV AWS_SECRET_ACCESS_KEY=NA 
ENV AWS_SESSION_TOKEN=NA

# Set the default command for the container
CMD [ "aws", "--version" ]